using WpfInspectionApp.Infrastructure;
using WpfInspectionApp.Models;

namespace WpfInspectionApp.ViewModels;

public sealed record AlignPanelModelState(
    string SelectedAlgorithm,
    int Threshold2D,
    int Threshold2DMax,
    int Threshold3D,
    int Threshold3DMax,
    int EdgeGain,
    bool Use2D,
    bool Use3D,
    bool UseEdge,
    int Range2DType,
    int Range3DType,
    bool InvertCheck,
    string HeightAverage,
    string SearchNum,
    string SearchMargin,
    string SearchSizeX,
    string SearchSizeY,
    bool SameSize,
    bool ShiftEnabled,
    string ShiftX,
    string ShiftY,
    bool AngleEnabled,
    string Angle,
    bool FillHole,
    string Filter,
    bool InspectionAreaCount,
    bool IpcUse,
    string IpcClass,
    string IpcPercent,
    bool PartTeachingUseCommonLibrary,
    bool PartTeachingUseLibraryPart,
    bool PartTeachingUseAutoTeaching,
    bool PartTeachingUseCadMatching,
    string PartTeachingLibraryMatchMode)
{
    public static AlignPanelModelState FromModel(InspectionModel model, string selectedAlgorithm)
    {
        return new AlignPanelModelState(
            selectedAlgorithm,
            model.Threshold2D,
            model.Threshold2DMax,
            model.Threshold3D,
            model.Threshold3DMax,
            model.EdgeGain,
            model.Use2D,
            model.Use3D,
            model.UseEdge,
            Net48Compat.Clamp(model.AlignRange2DType, 0, 3),
            Net48Compat.Clamp(model.AlignRange3DType, 0, 3),
            model.AlignInvertCheck,
            model.AlignHeightAverage.ToString("0.##"),
            Net48Compat.Clamp(model.AlignSearchNum, 1, 4).ToString(),
            model.AlignSearchMargin.ToString(),
            model.AlignSearchSizeX.ToString(),
            model.AlignSearchSizeY.ToString(),
            model.AlignSameSize,
            model.AlignShiftEnabled,
            model.AlignShiftX.ToString("0.00"),
            model.AlignShiftY.ToString("0.00"),
            model.AlignAngleEnabled,
            model.AlignAngle.ToString("0.##"),
            model.AlignFillHole,
            model.AlignFilter.ToString(),
            model.AlignInspectionAreaCount,
            model.IpcUse,
            model.IpcClass,
            model.IpcPercent.ToString("0.00"),
            model.PartTeachingUseCommonLibrary,
            model.PartTeachingUseLibraryPart,
            model.PartTeachingUseAutoTeaching,
            model.PartTeachingUseCadMatching,
            model.PartTeachingLibraryMatchMode);
    }
}
